// Mappa nomi paesi inglese → italiano (Natural Earth 110m)
const COUNTRY_NAMES_IT = {
  "Afghanistan": "Afghanistan",
  "Albania": "Albania",
  "Algeria": "Algeria",
  "Angola": "Angola",
  "Argentina": "Argentina",
  "Armenia": "Armenia",
  "Australia": "Australia",
  "Austria": "Austria",
  "Azerbaijan": "Azerbaigian",
  "Bahamas": "Bahamas",
  "Bangladesh": "Bangladesh",
  "Belarus": "Bielorussia",
  "Belgium": "Belgio",
  "Belize": "Belize",
  "Benin": "Benin",
  "Bhutan": "Bhutan",
  "Bolivia": "Bolivia",
  "Bosnia and Herzegovina": "Bosnia ed Erzegovina",
  "Botswana": "Botswana",
  "Brazil": "Brasile",
  "Brunei": "Brunei",
  "Bulgaria": "Bulgaria",
  "Burkina Faso": "Burkina Faso",
  "Burundi": "Burundi",
  "Cambodia": "Cambogia",
  "Cameroon": "Camerun",
  "Canada": "Canada",
  "Central African Republic": "Repubblica Centrafricana",
  "Chad": "Ciad",
  "Chile": "Cile",
  "China": "Cina",
  "Colombia": "Colombia",
  "Democratic Republic of the Congo": "Rep. Dem. del Congo",
  "Republic of the Congo": "Rep. del Congo",
  "Republic of Congo": "Rep. del Congo",
  "Costa Rica": "Costa Rica",
  "Croatia": "Croazia",
  "Cuba": "Cuba",
  "Cyprus": "Cipro",
  "Czech Republic": "Repubblica Ceca",
  "Czechia": "Repubblica Ceca",
  "Denmark": "Danimarca",
  "Djibouti": "Gibuti",
  "Dominican Republic": "Repubblica Dominicana",
  "East Timor": "Timor Est",
  "Timor-Leste": "Timor Est",
  "Ecuador": "Ecuador",
  "Egypt": "Egitto",
  "El Salvador": "El Salvador",
  "Equatorial Guinea": "Guinea Equatoriale",
  "Eritrea": "Eritrea",
  "Estonia": "Estonia",
  "eSwatini": "Eswatini",
  "Swaziland": "Eswatini",
  "Ethiopia": "Etiopia",
  "Fiji": "Figi",
  "Finland": "Finlandia",
  "France": "Francia",
  "French Southern and Antarctic Lands": "Terre Australi Francesi",
  "Gabon": "Gabon",
  "Gambia": "Gambia",
  "Georgia": "Georgia",
  "Germany": "Germania",
  "Ghana": "Ghana",
  "Greece": "Grecia",
  "Greenland": "Groenlandia",
  "Guatemala": "Guatemala",
  "Guinea": "Guinea",
  "Guinea-Bissau": "Guinea-Bissau",
  "Guyana": "Guyana",
  "Haiti": "Haiti",
  "Honduras": "Honduras",
  "Hungary": "Ungheria",
  "Iceland": "Islanda",
  "India": "India",
  "Indonesia": "Indonesia",
  "Iran": "Iran",
  "Iraq": "Iraq",
  "Ireland": "Irlanda",
  "Israel": "Israele",
  "Italy": "Italia",
  "Ivory Coast": "Costa d'Avorio",
  "Côte d'Ivoire": "Costa d'Avorio",
  "Jamaica": "Giamaica",
  "Japan": "Giappone",
  "Jordan": "Giordania",
  "Kazakhstan": "Kazakistan",
  "Kenya": "Kenya",
  "Kosovo": "Kosovo",
  "Kuwait": "Kuwait",
  "Kyrgyzstan": "Kirghizistan",
  "Laos": "Laos",
  "Latvia": "Lettonia",
  "Lebanon": "Libano",
  "Lesotho": "Lesotho",
  "Liberia": "Liberia",
  "Libya": "Libia",
  "Lithuania": "Lituania",
  "Luxembourg": "Lussemburgo",
  "Macedonia": "Macedonia del Nord",
  "North Macedonia": "Macedonia del Nord",
  "Madagascar": "Madagascar",
  "Malawi": "Malawi",
  "Malaysia": "Malesia",
  "Mali": "Mali",
  "Mauritania": "Mauritania",
  "Mexico": "Messico",
  "Moldova": "Moldavia",
  "Mongolia": "Mongolia",
  "Montenegro": "Montenegro",
  "Morocco": "Marocco",
  "Mozambique": "Mozambico",
  "Myanmar": "Myanmar",
  "Namibia": "Namibia",
  "Nepal": "Nepal",
  "Netherlands": "Paesi Bassi",
  "New Caledonia": "Nuova Caledonia",
  "New Zealand": "Nuova Zelanda",
  "Nicaragua": "Nicaragua",
  "Niger": "Niger",
  "Nigeria": "Nigeria",
  "North Korea": "Corea del Nord",
  "Norway": "Norvegia",
  "Oman": "Oman",
  "Pakistan": "Pakistan",
  "Palestine": "Palestina",
  "Panama": "Panama",
  "Papua New Guinea": "Papua Nuova Guinea",
  "Paraguay": "Paraguay",
  "Peru": "Perù",
  "Philippines": "Filippine",
  "Poland": "Polonia",
  "Portugal": "Portogallo",
  "Puerto Rico": "Porto Rico",
  "Qatar": "Qatar",
  "Romania": "Romania",
  "Russia": "Russia",
  "Rwanda": "Ruanda",
  "Saudi Arabia": "Arabia Saudita",
  "Senegal": "Senegal",
  "Serbia": "Serbia",
  "Sierra Leone": "Sierra Leone",
  "Slovakia": "Slovacchia",
  "Slovenia": "Slovenia",
  "Solomon Islands": "Isole Salomone",
  "Somalia": "Somalia",
  "Somaliland": "Somaliland",
  "South Africa": "Sudafrica",
  "South Korea": "Corea del Sud",
  "South Sudan": "Sud Sudan",
  "Spain": "Spagna",
  "Sri Lanka": "Sri Lanka",
  "Sudan": "Sudan",
  "Suriname": "Suriname",
  "Sweden": "Svezia",
  "Switzerland": "Svizzera",
  "Syria": "Siria",
  "Taiwan": "Taiwan",
  "Tajikistan": "Tagikistan",
  "United Republic of Tanzania": "Tanzania",
  "Tanzania": "Tanzania",
  "Thailand": "Thailandia",
  "The Bahamas": "Bahamas",
  "Togo": "Togo",
  "Trinidad and Tobago": "Trinidad e Tobago",
  "Tunisia": "Tunisia",
  "Turkey": "Turchia",
  "Turkmenistan": "Turkmenistan",
  "Uganda": "Uganda",
  "Ukraine": "Ucraina",
  "United Arab Emirates": "Emirati Arabi Uniti",
  "United Kingdom": "Regno Unito",
  "United States of America": "Stati Uniti",
  "United States": "Stati Uniti",
  "Uruguay": "Uruguay",
  "Uzbekistan": "Uzbekistan",
  "Venezuela": "Venezuela",
  "Vietnam": "Vietnam",
  "Western Sahara": "Sahara Occidentale",
  "Yemen": "Yemen",
  "Zambia": "Zambia",
  "Zimbabwe": "Zimbabwe",
  "Antarctica": "Antartide",
  "Northern Cyprus": "Cipro del Nord",
  "Falkland Islands": "Isole Falkland",
  "French Guiana": "Guyana Francese",
};

export function translateCountryName(nameEN) {
  return COUNTRY_NAMES_IT[nameEN] || nameEN;
}

export default COUNTRY_NAMES_IT;