// Database di app REALI di riferimento per ogni settore
// 4 app top per settore — app di singole attività/brand, NO marketplace

const SHOWCASE_APPS = {
  ristorazione: [
    {
      id: "starbucks",
      name: "Starbucks",
      description: "Ordina e paga dal telefono, accumula stelle e ricevi premi. L'app più usata al mondo per il food & beverage.",
      screenshot: "https://images.unsplash.com/photo-1504630083234-14187a9df0f5?w=400&h=800&fit=crop",
      features: ["Ordini mobile", "Programma fedeltà", "Pagamenti integrati", "Menu personalizzato"],
      color: "#00704A",
      url: "https://www.starbucks.com/rewards",
    },
    {
      id: "dominos",
      name: "Domino's Pizza",
      description: "Pizza tracker in tempo reale, ordini con un tap, promozioni esclusive. Leader mondiale nel food delivery.",
      screenshot: "https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?w=400&h=800&fit=crop",
      features: ["Pizza tracker live", "Ordine con 1 tap", "Promozioni push", "Delivery tracking"],
      color: "#006491",
      url: "https://www.dominos.it",
    },
    {
      id: "mcdonalds",
      name: "McDonald's",
      description: "Offerte esclusive, ordina e ritira, punti fedeltà MyMcDonald's Rewards. 40.000+ ristoranti nel mondo.",
      screenshot: "https://images.unsplash.com/photo-1551782450-a2132b4ba21d?w=400&h=800&fit=crop",
      features: ["Mobile ordering", "Offerte esclusive", "Loyalty rewards", "Drive-thru digitale"],
      color: "#FFC72C",
      url: "https://www.mcdonalds.it",
    },
    {
      id: "sweetgreen",
      name: "Sweetgreen",
      description: "Ordina insalate e bowl personalizzate. App con design minimale, programma fedeltà e pickup rapido.",
      screenshot: "https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=400&h=800&fit=crop",
      features: ["Ordini personalizzati", "Pickup rapido", "Programma fedeltà", "Menu stagionale"],
      color: "#2D7738",
      url: "https://www.sweetgreen.com",
    },
  ],
  beauty: [
    {
      id: "sephora",
      name: "Sephora",
      description: "Shopping beauty, virtual try-on, consulenze personalizzate. L'app premium del mondo beauty.",
      screenshot: "https://images.unsplash.com/photo-1596755389378-c31d21fd1273?w=400&h=800&fit=crop",
      features: ["Virtual try-on", "Beauty insider rewards", "Consulenze AI", "Shopping integrato"],
      color: "#000000",
      url: "https://www.sephora.it",
    },
    {
      id: "glossier",
      name: "Glossier",
      description: "Skincare e makeup essenziale con un design pulitissimo. Brand cult della Gen Z con milioni di fan.",
      screenshot: "https://images.unsplash.com/photo-1616394584738-fc6e612e71b9?w=400&h=800&fit=crop",
      features: ["E-commerce minimale", "Routine personalizzate", "Community", "Referral program"],
      color: "#F5C6C6",
      url: "https://www.glossier.com",
    },
    {
      id: "drybar",
      name: "Drybar",
      description: "Prenotazione piega e trattamenti capelli. L'app di un singolo brand di blow-dry bar con 150+ sedi.",
      screenshot: "https://images.unsplash.com/photo-1560066984-138dadb4c035?w=400&h=800&fit=crop",
      features: ["Prenotazione appuntamento", "Servizi e prezzi", "Loyalty program", "Sedi e orari"],
      color: "#FFD700",
      url: "https://www.thedrybar.com",
    },
    {
      id: "madison_reed",
      name: "Madison Reed",
      description: "Colorazione capelli premium con consulenza AI. Prenotazione in salone o acquisto kit colore a casa.",
      screenshot: "https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?w=400&h=800&fit=crop",
      features: ["Color match AI", "Prenotazione salone", "Shop prodotti", "Consulenza virtuale"],
      color: "#1C3A5F",
      url: "https://www.madison-reed.com",
    },
  ],
  fitness: [
    {
      id: "peloton",
      name: "Peloton",
      description: "Migliaia di classi live e on-demand: cardio, forza, yoga, meditazione. L'app fitness premium per eccellenza.",
      screenshot: "https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=400&h=800&fit=crop",
      features: ["Classi live", "Tracking progressi", "Community", "Piani personalizzati"],
      color: "#E12726",
      url: "https://www.onepeloton.com",
    },
    {
      id: "nike_training",
      name: "Nike Training Club",
      description: "Allenamenti gratuiti da trainer Nike. 200+ workout per ogni livello, dalla forza allo yoga.",
      screenshot: "https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=400&h=800&fit=crop",
      features: ["200+ workout", "Video HD", "Piani multi-settimana", "Apple Watch"],
      color: "#111111",
      url: "https://www.nike.com/ntc-app",
    },
    {
      id: "orangetheory",
      name: "Orangetheory Fitness",
      description: "L'app della catena di palestre boutique #1 al mondo. Prenotazione classi, heart rate tracking, risultati.",
      screenshot: "https://images.unsplash.com/photo-1574680096145-d05b474e2155?w=400&h=800&fit=crop",
      features: ["Prenotazione classi", "Heart rate live", "Statistiche allenamento", "Challenge community"],
      color: "#FF6900",
      url: "https://www.orangetheory.com",
    },
    {
      id: "technogym",
      name: "Technogym",
      description: "L'app della wellness company italiana leader mondiale. Connetti attrezzi, segui programmi, traccia tutto.",
      screenshot: "https://images.unsplash.com/photo-1517836357463-d25dfeac3438?w=400&h=800&fit=crop",
      features: ["Connessione attrezzi", "Programmi AI", "Video coaching", "Statistiche avanzate"],
      color: "#FFCC00",
      url: "https://www.technogym.com/it/technogym-app/",
    },
  ],
  ecommerce: [
    {
      id: "nike",
      name: "Nike",
      description: "Shopping, personalizzazione sneakers, SNKRS drops esclusivi. L'app e-commerce più iconica del pianeta.",
      screenshot: "https://images.unsplash.com/photo-1491553895911-0055eca6402d?w=400&h=800&fit=crop",
      features: ["Catalogo prodotti", "Nike By You", "SNKRS exclusive", "Member rewards"],
      color: "#111111",
      url: "https://www.nike.com",
    },
    {
      id: "zara",
      name: "Zara",
      description: "Fast fashion con design premium. Acquista online, ritira in negozio, prova a casa. 3000+ negozi nel mondo.",
      screenshot: "https://images.unsplash.com/photo-1441986300917-64674bd600d8?w=400&h=800&fit=crop",
      features: ["Catalogo completo", "Click & Collect", "Resi facili", "Notifiche restock"],
      color: "#000000",
      url: "https://www.zara.com/it/",
    },
    {
      id: "allbirds",
      name: "Allbirds",
      description: "Sneakers sostenibili con design minimale. Brand D2C con e-commerce pulito e carbon footprint tracker.",
      screenshot: "https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=400&h=800&fit=crop",
      features: ["Shop diretto", "Carbon footprint", "Design minimale", "Spedizioni gratuite"],
      color: "#2D5F2D",
      url: "https://www.allbirds.com",
    },
    {
      id: "warby_parker",
      name: "Warby Parker",
      description: "Occhiali da vista e sole con prova virtuale AR. Brand D2C con 200+ negozi e app premiata.",
      screenshot: "https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?w=400&h=800&fit=crop",
      features: ["Prova virtuale AR", "Home try-on", "Prescrizioni online", "Negozi + online"],
      color: "#00205B",
      url: "https://www.warbyparker.com",
    },
  ],
  immobiliare: [
    {
      id: "compass",
      name: "Compass Real Estate",
      description: "Agenzia immobiliare tech con app per agenti e acquirenti. Tour virtuali, ricerca AI, stime di mercato.",
      screenshot: "https://images.unsplash.com/photo-1560518883-ce09059eeffa?w=400&h=800&fit=crop",
      features: ["Ricerca AI", "Tour virtuali 3D", "Stime mercato", "Agente dedicato"],
      color: "#000000",
      url: "https://www.compass.com",
    },
    {
      id: "redfin",
      name: "Redfin",
      description: "Agenzia immobiliare digitale con commissioni ridotte. App con tour 3D, stime e agenti locali dedicati.",
      screenshot: "https://images.unsplash.com/photo-1582407947304-fd86f028f716?w=400&h=800&fit=crop",
      features: ["Tour 3D Redfin", "Stime in tempo reale", "Agenti locali", "Alert personalizzati"],
      color: "#A02021",
      url: "https://www.redfin.com",
    },
    {
      id: "airbnb",
      name: "Airbnb",
      description: "Affitta e scopri alloggi unici in tutto il mondo. Design premiato, esperienza utente eccezionale.",
      screenshot: "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=400&h=800&fit=crop",
      features: ["Esperienze uniche", "Prenotazione istantanea", "Superhost", "Mappa esplora"],
      color: "#FF5A5F",
      url: "https://www.airbnb.it",
    },
    {
      id: "gabetti",
      name: "Gabetti",
      description: "Agenzia immobiliare italiana storica. Ricerca immobili, valutazioni, contatto diretto con agente di zona.",
      screenshot: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=400&h=800&fit=crop",
      features: ["Ricerca immobili", "Valutazione online", "Agente dedicato", "Mutui e consulenze"],
      color: "#003DA5",
      url: "https://www.gabetti.it",
    },
  ],
  salute: [
    {
      id: "doctolib",
      name: "Doctolib",
      description: "Prenota visite mediche in 1 minuto. 80 milioni di utenti in Europa, 300.000+ professionisti.",
      screenshot: "https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?w=400&h=800&fit=crop",
      features: ["Prenotazione online", "Teleconsulto", "Ricette digitali", "Storico visite"],
      color: "#0076DC",
      url: "https://www.doctolib.it",
    },
    {
      id: "one_medical",
      name: "One Medical",
      description: "Clinica medica premium con app per prenotazioni, videoconsulti e messaggistica diretta col proprio medico.",
      screenshot: "https://images.unsplash.com/photo-1631217868264-e5b90bb7e133?w=400&h=800&fit=crop",
      features: ["Prenotazione in giornata", "Videoconsulto", "Chat col medico", "Rinnovo prescrizioni"],
      color: "#1B4D3E",
      url: "https://www.onemedical.com",
    },
    {
      id: "mindbody",
      name: "Mindbody",
      description: "Prenotazione lezioni e appuntamenti per studi di yoga, pilates, wellness. App usata da 58.000+ studi.",
      screenshot: "https://images.unsplash.com/photo-1559757175-5700dde675bc?w=400&h=800&fit=crop",
      features: ["Prenota lezioni", "Orari in tempo reale", "Check-in digitale", "Pacchetti e abbonamenti"],
      color: "#00A98F",
      url: "https://www.mindbodyonline.com",
    },
    {
      id: "humanitas",
      name: "Humanitas",
      description: "Il gruppo ospedaliero italiano di eccellenza. App per prenotare visite, referti online, accesso rapido.",
      screenshot: "https://images.unsplash.com/photo-1587854692152-cbe660dbde88?w=400&h=800&fit=crop",
      features: ["Prenotazione visite", "Referti online", "Percorsi di cura", "Accesso rapido"],
      color: "#0072BC",
      url: "https://www.humanitas.it",
    },
  ],
  turismo: [
    {
      id: "hilton",
      name: "Hilton Honors",
      description: "L'app della catena Hilton: check-in digitale, chiave camera sullo smartphone, punti fedeltà, upgrade.",
      screenshot: "https://images.unsplash.com/photo-1566073771259-6a8506099945?w=400&h=800&fit=crop",
      features: ["Digital key", "Check-in mobile", "Punti Honors", "Scelta camera"],
      color: "#003580",
      url: "https://www.hilton.com/en/hilton-honors/",
    },
    {
      id: "marriott",
      name: "Marriott Bonvoy",
      description: "L'app del più grande gruppo alberghiero al mondo. 30 brand, 8.000+ hotel, mobile check-in e chiave digitale.",
      screenshot: "https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?w=400&h=800&fit=crop",
      features: ["Mobile check-in", "Chiave digitale", "Rewards Bonvoy", "Chat concierge"],
      color: "#1C1C1C",
      url: "https://www.marriott.com/loyalty.mi",
    },
    {
      id: "airbnb_travel",
      name: "Airbnb",
      description: "Esperienze uniche e alloggi in tutto il mondo. Design premiato Apple Design Award.",
      screenshot: "https://images.unsplash.com/photo-1488085061387-422e29b40080?w=400&h=800&fit=crop",
      features: ["Alloggi unici", "Esperienze locali", "Wishlist condivise", "Prenotazione flessibile"],
      color: "#FF5A5F",
      url: "https://www.airbnb.it",
    },
    {
      id: "ryanair",
      name: "Ryanair",
      description: "L'app della compagnia aerea più usata in Europa. Prenotazione voli, boarding pass, offerte flash.",
      screenshot: "https://images.unsplash.com/photo-1469854523086-cc02fe5d8800?w=400&h=800&fit=crop",
      features: ["Prenotazione voli", "Boarding pass mobile", "Offerte flash", "Gestione prenotazione"],
      color: "#073590",
      url: "https://www.ryanair.com",
    },
  ],
  educazione: [
    {
      id: "duolingo",
      name: "Duolingo",
      description: "L'app di lingue più scaricata al mondo. Gamification, streak, AI tutor. Oltre 500 milioni di utenti.",
      screenshot: "https://images.unsplash.com/photo-1434030216411-0b793f4b4173?w=400&h=800&fit=crop",
      features: ["Gamification", "AI tutor", "40+ lingue", "Streak system"],
      color: "#58CC02",
      url: "https://www.duolingo.com",
    },
    {
      id: "masterclass",
      name: "MasterClass",
      description: "Impara dai migliori al mondo: Gordon Ramsay, Anna Wintour, Spike Lee. Produzione cinematografica.",
      screenshot: "https://images.unsplash.com/photo-1524178232363-1fb2b075b655?w=400&h=800&fit=crop",
      features: ["Istruttori celebrity", "Video 4K", "Workbook PDF", "Accesso illimitato"],
      color: "#000000",
      url: "https://www.masterclass.com",
    },
    {
      id: "babbel",
      name: "Babbel",
      description: "App di lingue creata da linguisti. Lezioni brevi, riconoscimento vocale, focus su conversazione reale.",
      screenshot: "https://images.unsplash.com/photo-1501504905252-473c47e087f8?w=400&h=800&fit=crop",
      features: ["Lezioni da 15 min", "Riconoscimento vocale", "14 lingue", "Certificato Babbel"],
      color: "#F56B2A",
      url: "https://www.babbel.com",
    },
    {
      id: "khan_academy",
      name: "Khan Academy",
      description: "Educazione gratuita per tutti. Matematica, scienze, programmazione — usata da 150 milioni di studenti.",
      screenshot: "https://images.unsplash.com/photo-1513475382585-d06e58bcb0e0?w=400&h=800&fit=crop",
      features: ["Corsi gratuiti", "Esercizi interattivi", "Progressi tracciati", "Tutte le materie"],
      color: "#14BF96",
      url: "https://www.khanacademy.org",
    },
  ],
  servizi: [
    {
      id: "slack",
      name: "Slack",
      description: "La piattaforma di comunicazione aziendale #1. Chat, canali, integrazioni, workflow automatizzati.",
      screenshot: "https://images.unsplash.com/photo-1497366216548-37526070297c?w=400&h=800&fit=crop",
      features: ["Chat in tempo reale", "Canali organizzati", "1000+ integrazioni", "Ricerca potente"],
      color: "#4A154B",
      url: "https://slack.com",
    },
    {
      id: "calendly",
      name: "Calendly",
      description: "Pianifica meeting senza email. L'app di scheduling usata da 20 milioni di professionisti.",
      screenshot: "https://images.unsplash.com/photo-1522071820081-009f0129c71c?w=400&h=800&fit=crop",
      features: ["Scheduling automatico", "Integrazioni calendar", "Link personalizzati", "Team pages"],
      color: "#006BFF",
      url: "https://calendly.com",
    },
    {
      id: "notion",
      name: "Notion",
      description: "Workspace all-in-one: note, wiki, progetti, database. Usata da team di ogni dimensione.",
      screenshot: "https://images.unsplash.com/photo-1531482615713-2afd69097998?w=400&h=800&fit=crop",
      features: ["Note e documenti", "Database relazionali", "Kanban board", "Template gallery"],
      color: "#000000",
      url: "https://www.notion.so",
    },
    {
      id: "hubspot",
      name: "HubSpot",
      description: "CRM, marketing, vendite e customer service in un'unica piattaforma. Usata da 200.000+ aziende.",
      screenshot: "https://images.unsplash.com/photo-1552664730-d307ca884978?w=400&h=800&fit=crop",
      features: ["CRM completo", "Email marketing", "Live chat", "Analytics avanzati"],
      color: "#FF7A59",
      url: "https://www.hubspot.com",
    },
  ],
};

// Map categorie wizard → chiave showcase
export const SHOWCASE_CATEGORY_MAP = {
  ristorazione: "ristorazione",
  beauty: "beauty",
  fitness: "fitness",
  ecommerce: "ecommerce",
  servizi: "servizi",
  immobiliare: "immobiliare",
  salute: "salute",
  turismo: "turismo",
  educazione: "educazione",
  altro: "servizi",
};

export default SHOWCASE_APPS;