// Database di app REALI di riferimento per ogni settore
// 4 app top per settore — brand riconosciuti a livello mondiale

const SHOWCASE_APPS = {
  ristorazione: [
    {
      id: "starbucks",
      name: "Starbucks",
      description: "Ordina e paga dal telefono, accumula stelle e ricevi premi. L'app più usata al mondo per il food & beverage.",
      screenshot: "https://images.unsplash.com/photo-1504630083234-14187a9df0f5?w=400&h=800&fit=crop",
      features: ["Ordini mobile", "Programma fedeltà", "Pagamenti integrati", "Menu personalizzato"],
      color: "#00704A",
      url: "https://www.starbucks.com/rewards",
    },
    {
      id: "dominos",
      name: "Domino's Pizza",
      description: "Pizza tracker in tempo reale, ordini con un tap, promozioni esclusive. Leader mondiale nel food delivery.",
      screenshot: "https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?w=400&h=800&fit=crop",
      features: ["Pizza tracker live", "Ordine con 1 tap", "Promozioni push", "Delivery tracking"],
      color: "#006491",
      url: "https://www.dominos.it",
    },
    {
      id: "thefork",
      name: "TheFork",
      description: "Prenota il ristorante perfetto, leggi recensioni, ottieni sconti fino al 50%. L'app #1 in Europa per la ristorazione.",
      screenshot: "https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=400&h=800&fit=crop",
      features: ["Prenotazione tavolo", "Recensioni verificate", "Sconti esclusivi", "Menu digitale"],
      color: "#00A86B",
      url: "https://www.thefork.it",
    },
    {
      id: "mcdonalds",
      name: "McDonald's",
      description: "Offerte esclusive, ordina e ritira, punti fedeltà MyMcDonald's Rewards. 40.000+ ristoranti nel mondo.",
      screenshot: "https://images.unsplash.com/photo-1551782450-a2132b4ba21d?w=400&h=800&fit=crop",
      features: ["Mobile ordering", "Offerte esclusive", "Loyalty rewards", "Drive-thru digitale"],
      color: "#FFC72C",
      url: "https://www.mcdonalds.it",
    },
  ],
  beauty: [
    {
      id: "fresha",
      name: "Fresha",
      description: "La piattaforma #1 al mondo per prenotare trattamenti beauty. Usata da 100.000+ saloni in 120 paesi.",
      screenshot: "https://images.unsplash.com/photo-1560066984-138dadb4c035?w=400&h=800&fit=crop",
      features: ["Prenotazione online", "Gestione appuntamenti", "Pagamenti integrati", "Promemoria automatici"],
      color: "#6C63FF",
      url: "https://www.fresha.com",
    },
    {
      id: "treatwell",
      name: "Treatwell",
      description: "Prenota parrucchiere, estetista, spa e massaggi. Leader europeo con 35.000+ saloni partner.",
      screenshot: "https://images.unsplash.com/photo-1570172619644-dfd03ed5d881?w=400&h=800&fit=crop",
      features: ["Prenotazione istantanea", "Recensioni clienti", "Listino prezzi", "Sconti last-minute"],
      color: "#FF6B81",
      url: "https://www.treatwell.it",
    },
    {
      id: "sephora",
      name: "Sephora",
      description: "Shopping beauty, virtual try-on, consulenze personalizzate. L'app premium del mondo beauty.",
      screenshot: "https://images.unsplash.com/photo-1596755389378-c31d21fd1273?w=400&h=800&fit=crop",
      features: ["Virtual try-on", "Beauty insider rewards", "Consulenze AI", "Shopping integrato"],
      color: "#000000",
      url: "https://www.sephora.it",
    },
    {
      id: "glossier",
      name: "Glossier",
      description: "Skincare e makeup essenziale con un design pulitissimo. Brand cult della Gen Z con milioni di fan.",
      screenshot: "https://images.unsplash.com/photo-1616394584738-fc6e612e71b9?w=400&h=800&fit=crop",
      features: ["E-commerce minimale", "Routine personalizzate", "Community", "Referral program"],
      color: "#F5C6C6",
      url: "https://www.glossier.com",
    },
  ],
  fitness: [
    {
      id: "peloton",
      name: "Peloton",
      description: "Migliaia di classi live e on-demand: cardio, forza, yoga, meditazione. L'app fitness premium per eccellenza.",
      screenshot: "https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=400&h=800&fit=crop",
      features: ["Classi live", "Tracking progressi", "Community", "Piani personalizzati"],
      color: "#E12726",
      url: "https://www.onepeloton.com",
    },
    {
      id: "nike_training",
      name: "Nike Training Club",
      description: "Allenamenti gratuiti da trainer Nike. 200+ workout per ogni livello, dalla forza allo yoga.",
      screenshot: "https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=400&h=800&fit=crop",
      features: ["200+ workout", "Video HD", "Piani multi-settimana", "Apple Watch"],
      color: "#111111",
      url: "https://www.nike.com/ntc-app",
    },
    {
      id: "myfitnesspal",
      name: "MyFitnessPal",
      description: "Il tracker nutrizionale #1 al mondo. Database di 14 milioni di alimenti, scanner barcode, diari.",
      screenshot: "https://images.unsplash.com/photo-1574680096145-d05b474e2155?w=400&h=800&fit=crop",
      features: ["Contacalorie", "Scanner barcode", "Obiettivi personalizzati", "Sincronizzazione wearable"],
      color: "#0070E0",
      url: "https://www.myfitnesspal.com",
    },
    {
      id: "technogym",
      name: "Technogym",
      description: "L'app della wellness company italiana leader mondiale. Connetti attrezzi, segui programmi, traccia tutto.",
      screenshot: "https://images.unsplash.com/photo-1517836357463-d25dfeac3438?w=400&h=800&fit=crop",
      features: ["Connessione attrezzi", "Programmi AI", "Video coaching", "Statistiche avanzate"],
      color: "#FFCC00",
      url: "https://www.technogym.com/it/technogym-app/",
    },
  ],
  ecommerce: [
    {
      id: "nike",
      name: "Nike",
      description: "Shopping, personalizzazione sneakers, SNKRS drops esclusivi. L'app e-commerce più iconica del pianeta.",
      screenshot: "https://images.unsplash.com/photo-1491553895911-0055eca6402d?w=400&h=800&fit=crop",
      features: ["Catalogo prodotti", "Nike By You", "SNKRS exclusive", "Member rewards"],
      color: "#111111",
      url: "https://www.nike.com",
    },
    {
      id: "zara",
      name: "Zara",
      description: "Fast fashion con design premium. Acquista online, ritira in negozio, prova a casa. 3000+ negozi nel mondo.",
      screenshot: "https://images.unsplash.com/photo-1441986300917-64674bd600d8?w=400&h=800&fit=crop",
      features: ["Catalogo completo", "Click & Collect", "Resi facili", "Notifiche restock"],
      color: "#000000",
      url: "https://www.zara.com/it/",
    },
    {
      id: "shopify_shop",
      name: "Shop by Shopify",
      description: "Tracking ordini universale, cashback, scoperta prodotti. L'app che unisce tutti i tuoi acquisti online.",
      screenshot: "https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=400&h=800&fit=crop",
      features: ["Tracking universale", "Cashback", "Shop Pay", "Scoperta prodotti"],
      color: "#5C6AC4",
      url: "https://shop.app",
    },
    {
      id: "etsy",
      name: "Etsy",
      description: "Marketplace per prodotti artigianali e vintage. 90 milioni di articoli unici da venditori indipendenti.",
      screenshot: "https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?w=400&h=800&fit=crop",
      features: ["Prodotti artigianali", "Personalizzazione", "Messaggi venditori", "Wishlist"],
      color: "#F56400",
      url: "https://www.etsy.com",
    },
  ],
  immobiliare: [
    {
      id: "zillow",
      name: "Zillow",
      description: "La piattaforma immobiliare #1 negli USA. Ricerca case, stime Zestimate, tour virtuali 3D.",
      screenshot: "https://images.unsplash.com/photo-1560518883-ce09059eeffa?w=400&h=800&fit=crop",
      features: ["Ricerca immobili", "Stime AI", "Tour virtuali", "Alert personalizzati"],
      color: "#006AFF",
      url: "https://www.zillow.com",
    },
    {
      id: "idealista",
      name: "Idealista",
      description: "Il portale immobiliare leader in Italia, Spagna e Portogallo. Milioni di annunci verificati.",
      screenshot: "https://images.unsplash.com/photo-1582407947304-fd86f028f716?w=400&h=800&fit=crop",
      features: ["Mappa interattiva", "Filtri avanzati", "Alert immobili", "Contatto diretto"],
      color: "#AEDD2B",
      url: "https://www.idealista.it",
    },
    {
      id: "immobiliare_it",
      name: "Immobiliare.it",
      description: "Il portale #1 in Italia per comprare, vendere e affittare casa. 1 milione+ annunci attivi.",
      screenshot: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=400&h=800&fit=crop",
      features: ["Ricerca smart", "Planimetrie", "Mutuo calcolatore", "Visite virtuali"],
      color: "#E4002B",
      url: "https://www.immobiliare.it",
    },
    {
      id: "airbnb",
      name: "Airbnb",
      description: "Affitta e scopri alloggi unici in tutto il mondo. Design premiato, esperienza utente eccezionale.",
      screenshot: "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=400&h=800&fit=crop",
      features: ["Esperienze uniche", "Prenotazione istantanea", "Superhost", "Mappa esplora"],
      color: "#FF5A5F",
      url: "https://www.airbnb.it",
    },
  ],
  salute: [
    {
      id: "doctolib",
      name: "Doctolib",
      description: "Prenota visite mediche in 1 minuto. 80 milioni di utenti in Europa, 300.000+ professionisti.",
      screenshot: "https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?w=400&h=800&fit=crop",
      features: ["Prenotazione online", "Teleconsulto", "Ricette digitali", "Storico visite"],
      color: "#0076DC",
      url: "https://www.doctolib.it",
    },
    {
      id: "miodottore",
      name: "MioDottore",
      description: "La piattaforma #1 in Italia per trovare specialisti e prenotare visite. Recensioni e disponibilità in tempo reale.",
      screenshot: "https://images.unsplash.com/photo-1631217868264-e5b90bb7e133?w=400&h=800&fit=crop",
      features: ["Cerca specialisti", "Prenotazione online", "Videoconsulto", "Recensioni verificate"],
      color: "#00B8A9",
      url: "https://www.miodottore.it",
    },
    {
      id: "ada_health",
      name: "Ada Health",
      description: "Symptom checker AI tra i più accurati al mondo. Analisi sintomi, suggerimenti e collegamento a medici.",
      screenshot: "https://images.unsplash.com/photo-1559757175-5700dde675bc?w=400&h=800&fit=crop",
      features: ["Symptom checker AI", "Report medici", "Collegamento dottori", "Storico salute"],
      color: "#7B61FF",
      url: "https://ada.com",
    },
    {
      id: "healthtap",
      name: "HealthTap",
      description: "Consulti medici 24/7 via chat e video. Accesso a migliaia di medici certificati per risposte immediate.",
      screenshot: "https://images.unsplash.com/photo-1587854692152-cbe660dbde88?w=400&h=800&fit=crop",
      features: ["Chat con medici", "Video consulti", "Prescrizioni online", "Disponibilità 24/7"],
      color: "#2EC4B6",
      url: "https://www.healthtap.com",
    },
  ],
  turismo: [
    {
      id: "booking",
      name: "Booking.com",
      description: "28 milioni di alloggi, voli, auto a noleggio. L'app travel più usata al mondo con Genius rewards.",
      screenshot: "https://images.unsplash.com/photo-1566073771259-6a8506099945?w=400&h=800&fit=crop",
      features: ["Hotel & voli", "Genius rewards", "Cancellazione gratuita", "App-only deals"],
      color: "#003580",
      url: "https://www.booking.com",
    },
    {
      id: "tripadvisor",
      name: "TripAdvisor",
      description: "1 miliardo di recensioni su hotel, ristoranti ed esperienze. La guida travel definitiva.",
      screenshot: "https://images.unsplash.com/photo-1488085061387-422e29b40080?w=400&h=800&fit=crop",
      features: ["Recensioni verificate", "Confronta prezzi", "Forum viaggiatori", "Guide città"],
      color: "#34E0A1",
      url: "https://www.tripadvisor.it",
    },
    {
      id: "airbnb_travel",
      name: "Airbnb",
      description: "Esperienze uniche e alloggi in tutto il mondo. Design premiato Apple Design Award.",
      screenshot: "https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?w=400&h=800&fit=crop",
      features: ["Alloggi unici", "Esperienze locali", "Wishlist condivise", "Prenotazione flessibile"],
      color: "#FF5A5F",
      url: "https://www.airbnb.it",
    },
    {
      id: "getYourGuide",
      name: "GetYourGuide",
      description: "Tour, attività e attrazioni in tutto il mondo. Biglietti skip-the-line e esperienze curate.",
      screenshot: "https://images.unsplash.com/photo-1469854523086-cc02fe5d8800?w=400&h=800&fit=crop",
      features: ["Tour guidati", "Skip the line", "Cancellazione gratuita", "Guide locali"],
      color: "#FF5533",
      url: "https://www.getyourguide.it",
    },
  ],
  educazione: [
    {
      id: "duolingo",
      name: "Duolingo",
      description: "L'app di lingue più scaricata al mondo. Gamification, streak, AI tutor. Oltre 500 milioni di utenti.",
      screenshot: "https://images.unsplash.com/photo-1434030216411-0b793f4b4173?w=400&h=800&fit=crop",
      features: ["Gamification", "AI tutor", "40+ lingue", "Streak system"],
      color: "#58CC02",
      url: "https://www.duolingo.com",
    },
    {
      id: "coursera",
      name: "Coursera",
      description: "Corsi dalle migliori università del mondo: Stanford, Yale, Google. Certificati professionali riconosciuti.",
      screenshot: "https://images.unsplash.com/photo-1501504905252-473c47e087f8?w=400&h=800&fit=crop",
      features: ["Corsi universitari", "Certificati", "Video lezioni", "Quiz interattivi"],
      color: "#0056D2",
      url: "https://www.coursera.org",
    },
    {
      id: "skillshare",
      name: "Skillshare",
      description: "Migliaia di classi creative: design, foto, business, marketing. Comunità di 12 milioni di creativi.",
      screenshot: "https://images.unsplash.com/photo-1513475382585-d06e58bcb0e0?w=400&h=800&fit=crop",
      features: ["Classi creative", "Progetti pratici", "Community", "Offline download"],
      color: "#00FF84",
      url: "https://www.skillshare.com",
    },
    {
      id: "masterclass",
      name: "MasterClass",
      description: "Impara dai migliori al mondo: Gordon Ramsay, Anna Wintour, Spike Lee. Produzione cinematografica.",
      screenshot: "https://images.unsplash.com/photo-1524178232363-1fb2b075b655?w=400&h=800&fit=crop",
      features: ["Istruttori celebrity", "Video 4K", "Workbook PDF", "Accesso illimitato"],
      color: "#000000",
      url: "https://www.masterclass.com",
    },
  ],
  servizi: [
    {
      id: "slack",
      name: "Slack",
      description: "La piattaforma di comunicazione aziendale #1. Chat, canali, integrazioni, workflow automatizzati.",
      screenshot: "https://images.unsplash.com/photo-1497366216548-37526070297c?w=400&h=800&fit=crop",
      features: ["Chat in tempo reale", "Canali organizzati", "1000+ integrazioni", "Ricerca potente"],
      color: "#4A154B",
      url: "https://slack.com",
    },
    {
      id: "calendly",
      name: "Calendly",
      description: "Pianifica meeting senza email. L'app di scheduling usata da 20 milioni di professionisti.",
      screenshot: "https://images.unsplash.com/photo-1522071820081-009f0129c71c?w=400&h=800&fit=crop",
      features: ["Scheduling automatico", "Integrazioni calendar", "Link personalizzati", "Team pages"],
      color: "#006BFF",
      url: "https://calendly.com",
    },
    {
      id: "notion",
      name: "Notion",
      description: "Workspace all-in-one: note, wiki, progetti, database. Usata da team di ogni dimensione.",
      screenshot: "https://images.unsplash.com/photo-1531482615713-2afd69097998?w=400&h=800&fit=crop",
      features: ["Note e documenti", "Database relazionali", "Kanban board", "Template gallery"],
      color: "#000000",
      url: "https://www.notion.so",
    },
    {
      id: "hubspot",
      name: "HubSpot",
      description: "CRM, marketing, vendite e customer service in un'unica piattaforma. Usata da 200.000+ aziende.",
      screenshot: "https://images.unsplash.com/photo-1552664730-d307ca884978?w=400&h=800&fit=crop",
      features: ["CRM completo", "Email marketing", "Live chat", "Analytics avanzati"],
      color: "#FF7A59",
      url: "https://www.hubspot.com",
    },
  ],
};

// Map categorie wizard → chiave showcase
export const SHOWCASE_CATEGORY_MAP = {
  ristorazione: "ristorazione",
  beauty: "beauty",
  fitness: "fitness",
  ecommerce: "ecommerce",
  servizi: "servizi",
  immobiliare: "immobiliare",
  salute: "salute",
  turismo: "turismo",
  educazione: "educazione",
  altro: "servizi",
};

export default SHOWCASE_APPS;