// ============================================================
// TEMPLATE LIBRARY — 50 template professionali (5 x 10 categorie)
// Ogni template ha stile, layout, UX e target radicalmente diversi
// ============================================================

const TEMPLATE_LIBRARY = [

  // ══════════════════════════════════════════════════════════
  // RISTORAZIONE (5 template)
  // ══════════════════════════════════════════════════════════

  {
    id: "resto_premium",
    name: "Ristorante Premium",
    category: "ristorazione",
    target: "Ristoranti eleganti, fine dining",
    ux: "immersive", // esperienza immersiva visiva
    primaryColor: "#1a1a1a",
    secondaryColor: "#0a0a0a",
    accentColor: "#c9a96e",
    darkMode: true,
    fontStyle: "serif",
    heroImage: "https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=600",
    previewItems: ["Filetto al Tartufo", "Risotto Zafferano", "Crème Brûlée"],
    preview: {
      headerBg: "#0a0a0a",
      headerText: "#c9a96e",
      cardBg: "#1a1a1a",
      accent: "#c9a96e",
      bodyBg: "#0a0a0a",
      layoutStyle: "immersive",
      heroImage: "https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=600",
    },
    features: ["Menu degustazione", "Prenotazione tavoli", "Lista vini", "Chef's table"],
  },
  {
    id: "pizzeria_delivery",
    name: "Pizzeria Delivery",
    category: "ristorazione",
    target: "Pizzerie con consegna a domicilio",
    ux: "quick", // esperienza veloce con azioni rapide
    primaryColor: "#e63946",
    secondaryColor: "#ffffff",
    accentColor: "#ff6b6b",
    darkMode: false,
    fontStyle: "sans-serif",
    heroImage: "https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?w=600",
    previewItems: ["Margherita", "Diavola", "Quattro Formaggi"],
    preview: {
      headerBg: "#e63946",
      headerText: "#ffffff",
      cardBg: "#ffffff",
      accent: "#e63946",
      bodyBg: "#fef9f9",
      layoutStyle: "quick-actions",
    },
    features: ["Ordini online", "Tracking consegna", "Menu builder", "Promozioni flash"],
  },
  {
    id: "streetfood_geo",
    name: "Street Food",
    category: "ristorazione",
    target: "Food truck, street food, chioschi",
    ux: "guided", // esperienza guidata passo-passo
    primaryColor: "#f5a623",
    secondaryColor: "#1a1a2e",
    accentColor: "#ffcc02",
    darkMode: true,
    fontStyle: "sans-serif",
    heroImage: "https://images.unsplash.com/photo-1551782450-a2132b4ba21d?w=600",
    previewItems: ["Smash Burger", "Loaded Fries", "Milkshake"],
    preview: {
      headerBg: "#1a1a2e",
      headerText: "#f5a623",
      cardBg: "#252540",
      accent: "#f5a623",
      bodyBg: "#12122a",
      layoutStyle: "cards",
    },
    features: ["Menu rapido", "Geolocalizzazione", "Ordine al volo", "Recensioni"],
  },
  {
    id: "gourmet_events",
    name: "Gourmet & Eventi",
    category: "ristorazione",
    target: "Ristoranti gourmet con eventi chef",
    ux: "dashboard", // esperienza gestionale
    primaryColor: "#2d2d2d",
    secondaryColor: "#f5f0e8",
    accentColor: "#8b6f47",
    darkMode: false,
    fontStyle: "serif",
    heroImage: "https://images.unsplash.com/photo-1552566626-52f8b828add9?w=600",
    previewItems: ["Menu 7 Portate", "Wine Pairing", "Chef's Experience"],
    preview: {
      headerBg: "#f5f0e8",
      headerText: "#2d2d2d",
      cardBg: "#ffffff",
      accent: "#8b6f47",
      bodyBg: "#f5f0e8",
      layoutStyle: "dashboard",
    },
    features: ["Menu degustazione", "Eventi privati", "Calendario chef", "Prenotazioni VIP"],
  },
  {
    id: "bar_nightlife",
    name: "Bar & Nightlife",
    category: "ristorazione",
    target: "Bar, cocktail bar, locali serali",
    ux: "catalog", // esperienza catalogo
    primaryColor: "#6c5ce7",
    secondaryColor: "#0d0d1a",
    accentColor: "#a29bfe",
    darkMode: true,
    fontStyle: "sans-serif",
    heroImage: "https://images.unsplash.com/photo-1563379091339-03b21ab4a4f4?w=600",
    previewItems: ["Negroni Sbagliato", "Aperol Spritz", "Mojito"],
    preview: {
      headerBg: "transparent",
      headerText: "#ffffff",
      cardBg: "#1a1a2e",
      accent: "#a29bfe",
      bodyBg: "#0d0d1a",
      layoutStyle: "immersive",
      heroImage: "https://images.unsplash.com/photo-1563379091339-03b21ab4a4f4?w=600",
    },
    features: ["Drink list", "Eventi serali", "Prenotazione tavoli", "DJ set calendar"],
  },

  // ══════════════════════════════════════════════════════════
  // BEAUTY & WELLNESS (5 template)
  // ══════════════════════════════════════════════════════════

  {
    id: "beauty_luxury",
    name: "Luxury Spa",
    category: "beauty",
    target: "Spa di lusso, centri benessere premium",
    ux: "immersive",
    primaryColor: "#2c1810",
    secondaryColor: "#f8f3ee",
    accentColor: "#b8860b",
    darkMode: false,
    fontStyle: "serif",
    heroImage: "https://images.unsplash.com/photo-1570172619644-dfd03ed5d881?w=600",
    previewItems: ["Hot Stone Massage", "Facial Gold", "Aromatherapy"],
    preview: {
      headerBg: "#f8f3ee",
      headerText: "#2c1810",
      cardBg: "#ffffff",
      accent: "#b8860b",
      bodyBg: "#f8f3ee",
      layoutStyle: "minimal",
    },
    features: ["Prenotazione trattamenti", "Pacchetti benessere", "Schede cliente", "Membership VIP"],
  },
  {
    id: "beauty_salon",
    name: "Hair Salon",
    category: "beauty",
    target: "Parrucchieri, saloni di bellezza",
    ux: "quick",
    primaryColor: "#e91e63",
    secondaryColor: "#ffffff",
    accentColor: "#f48fb1",
    darkMode: false,
    fontStyle: "sans-serif",
    heroImage: "https://images.unsplash.com/photo-1560066984-138dadb4c035?w=600",
    previewItems: ["Taglio & Piega", "Colore", "Trattamento Cheratina"],
    preview: {
      headerBg: "#e91e63",
      headerText: "#ffffff",
      cardBg: "#ffffff",
      accent: "#e91e63",
      bodyBg: "#fff5f8",
      layoutStyle: "quick-actions",
    },
    features: ["Agenda operatori", "Prenotazione rapida", "Portfolio lavori", "Promozioni"],
  },
  {
    id: "beauty_minimal",
    name: "Estetica Minimal",
    category: "beauty",
    target: "Centri estetici moderni, skincare",
    ux: "guided",
    primaryColor: "#333333",
    secondaryColor: "#fafafa",
    accentColor: "#90caf9",
    darkMode: false,
    fontStyle: "sans-serif",
    heroImage: "https://images.unsplash.com/photo-1616394584738-fc6e612e71b9?w=600",
    previewItems: ["Pulizia Viso", "Peeling", "Laser Therapy"],
    preview: {
      headerBg: "#fafafa",
      headerText: "#333333",
      cardBg: "#ffffff",
      accent: "#90caf9",
      bodyBg: "#f5f5f5",
      layoutStyle: "minimal",
    },
    features: ["Percorsi guidati", "Schede trattamento", "Before/After gallery", "Consulenza AI"],
  },
  {
    id: "beauty_wellness",
    name: "Wellness Hub",
    category: "beauty",
    target: "Centri olistici, yoga, meditazione",
    ux: "dashboard",
    primaryColor: "#4a7c59",
    secondaryColor: "#f0f4ec",
    accentColor: "#81c784",
    darkMode: false,
    fontStyle: "serif",
    heroImage: "https://images.unsplash.com/photo-1570172619644-dfd03ed5d881?w=600",
    previewItems: ["Yoga Session", "Sound Healing", "Meditation"],
    preview: {
      headerBg: "#f0f4ec",
      headerText: "#4a7c59",
      cardBg: "#ffffff",
      accent: "#81c784",
      bodyBg: "#f0f4ec",
      layoutStyle: "dashboard",
    },
    features: ["Calendario corsi", "Progressi personali", "Community", "Piani abbonamento"],
  },
  {
    id: "beauty_nails",
    name: "Nail Art Studio",
    category: "beauty",
    target: "Nail bar, centri manicure",
    ux: "catalog",
    primaryColor: "#ff6f91",
    secondaryColor: "#1a0a10",
    accentColor: "#ffc75f",
    darkMode: true,
    fontStyle: "sans-serif",
    heroImage: "https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?w=600",
    previewItems: ["French Manicure", "Nail Art Design", "Gel Extension"],
    preview: {
      headerBg: "#1a0a10",
      headerText: "#ff6f91",
      cardBg: "#2a1520",
      accent: "#ffc75f",
      bodyBg: "#1a0a10",
      layoutStyle: "cards",
    },
    features: ["Catalogo design", "Prenotazione", "Portfolio Instagram", "Fidelity card"],
  },

  // ══════════════════════════════════════════════════════════
  // FITNESS & SPORT (5 template)
  // ══════════════════════════════════════════════════════════

  {
    id: "fitness_gym",
    name: "Gym Pro",
    category: "fitness",
    target: "Palestre, centri fitness",
    ux: "dashboard",
    primaryColor: "#ff5722",
    secondaryColor: "#121212",
    accentColor: "#ff9800",
    darkMode: true,
    fontStyle: "sans-serif",
    heroImage: "https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=600",
    previewItems: ["CrossFit", "Functional", "Cardio Zone"],
    preview: {
      headerBg: "#121212",
      headerText: "#ff5722",
      cardBg: "#1e1e1e",
      accent: "#ff5722",
      bodyBg: "#121212",
      layoutStyle: "dashboard",
    },
    features: ["Prenotazione corsi", "Schede allenamento", "Progressi", "Abbonamenti"],
  },
  {
    id: "fitness_trainer",
    name: "Personal Trainer",
    category: "fitness",
    target: "Personal trainer, coaching individuale",
    ux: "guided",
    primaryColor: "#00bcd4",
    secondaryColor: "#0a0a0a",
    accentColor: "#26c6da",
    darkMode: true,
    fontStyle: "sans-serif",
    heroImage: "https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=600",
    previewItems: ["1-to-1 Session", "Program Builder", "Progress Track"],
    preview: {
      headerBg: "transparent",
      headerText: "#ffffff",
      cardBg: "#1a1a2e",
      accent: "#00bcd4",
      bodyBg: "#0a0a0a",
      layoutStyle: "immersive",
      heroImage: "https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=600",
    },
    features: ["Programmi personalizzati", "Video tutorial", "Nutrizione", "Chat trainer"],
  },
  {
    id: "fitness_yoga",
    name: "Yoga Studio",
    category: "fitness",
    target: "Studi yoga, pilates, meditazione",
    ux: "immersive",
    primaryColor: "#7e57c2",
    secondaryColor: "#f5f0ff",
    accentColor: "#b39ddb",
    darkMode: false,
    fontStyle: "serif",
    heroImage: "https://images.unsplash.com/photo-1574680096145-d05b474e2155?w=600",
    previewItems: ["Hatha Yoga", "Vinyasa Flow", "Meditation"],
    preview: {
      headerBg: "#f5f0ff",
      headerText: "#7e57c2",
      cardBg: "#ffffff",
      accent: "#b39ddb",
      bodyBg: "#f5f0ff",
      layoutStyle: "minimal",
    },
    features: ["Calendario lezioni", "Streaming live", "Percorsi guidati", "Community"],
  },
  {
    id: "fitness_club",
    name: "Sport Club",
    category: "fitness",
    target: "Centri sportivi, club multisport",
    ux: "quick",
    primaryColor: "#1e88e5",
    secondaryColor: "#ffffff",
    accentColor: "#42a5f5",
    darkMode: false,
    fontStyle: "sans-serif",
    heroImage: "https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=600",
    previewItems: ["Tennis", "Nuoto", "Padel"],
    preview: {
      headerBg: "#1e88e5",
      headerText: "#ffffff",
      cardBg: "#ffffff",
      accent: "#1e88e5",
      bodyBg: "#f0f7ff",
      layoutStyle: "quick-actions",
    },
    features: ["Prenotazione campi", "Tornei", "Classifica", "Membership"],
  },
  {
    id: "fitness_outdoor",
    name: "Outdoor Adventures",
    category: "fitness",
    target: "Attività outdoor, trekking, escursioni",
    ux: "catalog",
    primaryColor: "#2e7d32",
    secondaryColor: "#e8f5e9",
    accentColor: "#66bb6a",
    darkMode: false,
    fontStyle: "sans-serif",
    heroImage: "https://images.unsplash.com/photo-1551632811-561732d1e306?w=600",
    previewItems: ["Trekking Dolomiti", "Mountain Bike", "Arrampicata"],
    preview: {
      headerBg: "#e8f5e9",
      headerText: "#2e7d32",
      cardBg: "#ffffff",
      accent: "#66bb6a",
      bodyBg: "#e8f5e9",
      layoutStyle: "cards",
    },
    features: ["Catalogo attività", "Calendario uscite", "Difficoltà & Mappe", "Gruppi"],
  },

  // ══════════════════════════════════════════════════════════
  // E-COMMERCE (5 template)
  // ══════════════════════════════════════════════════════════

  {
    id: "ecom_minimal",
    name: "Shop Minimal",
    category: "ecommerce",
    target: "Brand artigianali, design, prodotti curati",
    ux: "immersive",
    primaryColor: "#1a1a1a",
    secondaryColor: "#ffffff",
    accentColor: "#333333",
    darkMode: false,
    fontStyle: "sans-serif",
    heroImage: "https://images.unsplash.com/photo-1441986300917-64674bd600d8?w=600",
    previewItems: ["Ceramic Vase", "Linen Shirt", "Leather Bag"],
    preview: {
      headerBg: "#ffffff",
      headerText: "#1a1a1a",
      cardBg: "#ffffff",
      accent: "#1a1a1a",
      bodyBg: "#fafafa",
      layoutStyle: "minimal",
    },
    features: ["Catalogo prodotti", "Carrello", "Wishlist", "Checkout"],
  },
  {
    id: "ecom_fashion",
    name: "Fashion Brand",
    category: "ecommerce",
    target: "Brand moda, abbigliamento, accessori",
    ux: "catalog",
    primaryColor: "#000000",
    secondaryColor: "#f5f5f5",
    accentColor: "#d4a574",
    darkMode: false,
    fontStyle: "serif",
    heroImage: "https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?w=600",
    previewItems: ["Summer Collection", "Accessories", "Limited Edition"],
    preview: {
      headerBg: "#ffffff",
      headerText: "#000000",
      cardBg: "#ffffff",
      accent: "#d4a574",
      bodyBg: "#f5f5f5",
      layoutStyle: "cards",
    },
    features: ["Lookbook", "Collezioni", "Size guide", "Brand story"],
  },
  {
    id: "ecom_marketplace",
    name: "Marketplace",
    category: "ecommerce",
    target: "Multi-vendor, marketplace locale",
    ux: "quick",
    primaryColor: "#ff6f00",
    secondaryColor: "#ffffff",
    accentColor: "#ffa726",
    darkMode: false,
    fontStyle: "sans-serif",
    heroImage: "https://images.unsplash.com/photo-1441986300917-64674bd600d8?w=600",
    previewItems: ["Elettronica", "Casa & Giardino", "Sport"],
    preview: {
      headerBg: "#ff6f00",
      headerText: "#ffffff",
      cardBg: "#ffffff",
      accent: "#ff6f00",
      bodyBg: "#fff8f0",
      layoutStyle: "quick-actions",
    },
    features: ["Categorie", "Filtri avanzati", "Multi-vendor", "Offerte flash"],
  },
  {
    id: "ecom_subscription",
    name: "Subscription Box",
    category: "ecommerce",
    target: "Box in abbonamento, prodotti ricorrenti",
    ux: "guided",
    primaryColor: "#6c5ce7",
    secondaryColor: "#f8f7ff",
    accentColor: "#a29bfe",
    darkMode: false,
    fontStyle: "sans-serif",
    heroImage: "https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=600",
    previewItems: ["Box Mensile", "Piano Premium", "Box Regalo"],
    preview: {
      headerBg: "#f8f7ff",
      headerText: "#6c5ce7",
      cardBg: "#ffffff",
      accent: "#a29bfe",
      bodyBg: "#f8f7ff",
      layoutStyle: "dashboard",
    },
    features: ["Piani abbonamento", "Personalizza box", "Storico spedizioni", "Referral"],
  },
  {
    id: "ecom_luxury",
    name: "Luxury Store",
    category: "ecommerce",
    target: "Prodotti di lusso, gioielli, orologi",
    ux: "dashboard",
    primaryColor: "#c9a96e",
    secondaryColor: "#0d0d0d",
    accentColor: "#e8c49a",
    darkMode: true,
    fontStyle: "serif",
    heroImage: "https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=600",
    previewItems: ["Diamond Ring", "Swiss Watch", "Silk Scarf"],
    preview: {
      headerBg: "#0d0d0d",
      headerText: "#c9a96e",
      cardBg: "#1a1a1a",
      accent: "#c9a96e",
      bodyBg: "#0d0d0d",
      layoutStyle: "immersive",
      heroImage: "https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=600",
    },
    features: ["Collezione esclusiva", "Concierge", "Autenticità certificata", "Spedizione premium"],
  },

  // ══════════════════════════════════════════════════════════
  // SERVIZI PROFESSIONALI (5 template)
  // ══════════════════════════════════════════════════════════

  {
    id: "serv_consulting",
    name: "Studio Consulenza",
    category: "servizi",
    target: "Studi di consulenza, strategia aziendale",
    ux: "dashboard",
    primaryColor: "#1e3a5f",
    secondaryColor: "#f4f6f9",
    accentColor: "#3498db",
    darkMode: false,
    fontStyle: "sans-serif",
    heroImage: "https://images.unsplash.com/photo-1497366216548-37526070297c?w=600",
    previewItems: ["Strategia", "Analisi", "Report"],
    preview: {
      headerBg: "#1e3a5f",
      headerText: "#ffffff",
      cardBg: "#ffffff",
      accent: "#3498db",
      bodyBg: "#f4f6f9",
      layoutStyle: "dashboard",
    },
    features: ["Calendario appuntamenti", "Gestione clienti", "Report", "Fatturazione"],
  },
  {
    id: "serv_agency",
    name: "Agenzia Creativa",
    category: "servizi",
    target: "Agenzie marketing, comunicazione, digital",
    ux: "immersive",
    primaryColor: "#ff4081",
    secondaryColor: "#0a0a0a",
    accentColor: "#ff80ab",
    darkMode: true,
    fontStyle: "sans-serif",
    heroImage: "https://images.unsplash.com/photo-1497366216548-37526070297c?w=600",
    previewItems: ["Branding", "Social Media", "Web Design"],
    preview: {
      headerBg: "transparent",
      headerText: "#ffffff",
      cardBg: "#1a1a2e",
      accent: "#ff4081",
      bodyBg: "#0a0a0a",
      layoutStyle: "immersive",
      heroImage: "https://images.unsplash.com/photo-1497366216548-37526070297c?w=600",
    },
    features: ["Portfolio", "Case studies", "Richiedi preventivo", "Team"],
  },
  {
    id: "serv_legal",
    name: "Studio Legale",
    category: "servizi",
    target: "Avvocati, studi legali, notai",
    ux: "guided",
    primaryColor: "#37474f",
    secondaryColor: "#eceff1",
    accentColor: "#546e7a",
    darkMode: false,
    fontStyle: "serif",
    heroImage: "https://images.unsplash.com/photo-1497366216548-37526070297c?w=600",
    previewItems: ["Diritto Civile", "Diritto Penale", "Consulenza"],
    preview: {
      headerBg: "#eceff1",
      headerText: "#37474f",
      cardBg: "#ffffff",
      accent: "#546e7a",
      bodyBg: "#eceff1",
      layoutStyle: "minimal",
    },
    features: ["Aree di competenza", "Prenota consulenza", "Documenti", "FAQ legali"],
  },
  {
    id: "serv_accountant",
    name: "Commercialista",
    category: "servizi",
    target: "Commercialisti, consulenti fiscali",
    ux: "quick",
    primaryColor: "#00695c",
    secondaryColor: "#ffffff",
    accentColor: "#26a69a",
    darkMode: false,
    fontStyle: "sans-serif",
    heroImage: "https://images.unsplash.com/photo-1497366216548-37526070297c?w=600",
    previewItems: ["Dichiarazioni", "Bilanci", "Consulenza fiscale"],
    preview: {
      headerBg: "#00695c",
      headerText: "#ffffff",
      cardBg: "#ffffff",
      accent: "#26a69a",
      bodyBg: "#f0faf8",
      layoutStyle: "quick-actions",
    },
    features: ["Scadenziario", "Upload documenti", "Chat consulente", "Dashboard fiscale"],
  },
  {
    id: "serv_freelancer",
    name: "Freelancer Portfolio",
    category: "servizi",
    target: "Freelancer, designer, sviluppatori",
    ux: "catalog",
    primaryColor: "#6366f1",
    secondaryColor: "#f5f3ff",
    accentColor: "#818cf8",
    darkMode: false,
    fontStyle: "sans-serif",
    heroImage: "https://images.unsplash.com/photo-1497366216548-37526070297c?w=600",
    previewItems: ["Web Design", "App Mobile", "Branding"],
    preview: {
      headerBg: "#f5f3ff",
      headerText: "#6366f1",
      cardBg: "#ffffff",
      accent: "#818cf8",
      bodyBg: "#f5f3ff",
      layoutStyle: "cards",
    },
    features: ["Portfolio progetti", "Servizi & Prezzi", "Contattami", "Testimonial"],
  },

  // ══════════════════════════════════════════════════════════
  // IMMOBILIARE (5 template)
  // ══════════════════════════════════════════════════════════

  {
    id: "immo_agency",
    name: "Agenzia Immobiliare",
    category: "immobiliare",
    target: "Agenzie immobiliari tradizionali",
    ux: "quick",
    primaryColor: "#1565c0",
    secondaryColor: "#ffffff",
    accentColor: "#42a5f5",
    darkMode: false,
    fontStyle: "sans-serif",
    heroImage: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=600",
    previewItems: ["Trilocale Centro", "Villa Collina", "Loft Industriale"],
    preview: {
      headerBg: "#1565c0",
      headerText: "#ffffff",
      cardBg: "#ffffff",
      accent: "#42a5f5",
      bodyBg: "#f0f4ff",
      layoutStyle: "quick-actions",
    },
    features: ["Ricerca immobili", "Filtri avanzati", "Contatta agente", "Visite virtuali"],
  },
  {
    id: "immo_luxury",
    name: "Luxury Real Estate",
    category: "immobiliare",
    target: "Immobili di lusso, ville, attici",
    ux: "immersive",
    primaryColor: "#d4a574",
    secondaryColor: "#0d0d0d",
    accentColor: "#e8c49a",
    darkMode: true,
    fontStyle: "serif",
    heroImage: "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=600",
    previewItems: ["Villa Panoramica", "Attico Terrazza", "Castello Toscana"],
    preview: {
      headerBg: "transparent",
      headerText: "#ffffff",
      cardBg: "#1a1a1a",
      accent: "#d4a574",
      bodyBg: "#0d0d0d",
      layoutStyle: "immersive",
      heroImage: "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=600",
    },
    features: ["Gallery immersiva", "Tour virtuale 3D", "Concierge", "Portfolio esclusivo"],
  },
  {
    id: "immo_rental",
    name: "Affitti Brevi",
    category: "immobiliare",
    target: "Affitti turistici, case vacanza, B&B",
    ux: "catalog",
    primaryColor: "#ff5252",
    secondaryColor: "#ffffff",
    accentColor: "#ff867c",
    darkMode: false,
    fontStyle: "sans-serif",
    heroImage: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=600",
    previewItems: ["Appartamento Mare", "Casa Montagna", "Loft Città"],
    preview: {
      headerBg: "#ffffff",
      headerText: "#333333",
      cardBg: "#ffffff",
      accent: "#ff5252",
      bodyBg: "#fafafa",
      layoutStyle: "cards",
    },
    features: ["Calendario disponibilità", "Prenotazione diretta", "Recensioni ospiti", "Check-in digitale"],
  },
  {
    id: "immo_newbuild",
    name: "Nuove Costruzioni",
    category: "immobiliare",
    target: "Costruttori, nuovi progetti residenziali",
    ux: "guided",
    primaryColor: "#2c3e50",
    secondaryColor: "#f8f6f3",
    accentColor: "#c9956b",
    darkMode: false,
    fontStyle: "serif",
    heroImage: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=600",
    previewItems: ["Residenza Park", "Loft Urban", "Green Village"],
    preview: {
      headerBg: "#f8f6f3",
      headerText: "#2c3e50",
      cardBg: "#ffffff",
      accent: "#c9956b",
      bodyBg: "#f8f6f3",
      layoutStyle: "dashboard",
    },
    features: ["Progetti in vendita", "Configuratore", "Planimetrie", "Stato lavori"],
  },
  {
    id: "immo_invest",
    name: "Real Estate Invest",
    category: "immobiliare",
    target: "Investimenti immobiliari, crowdfunding",
    ux: "dashboard",
    primaryColor: "#00897b",
    secondaryColor: "#e0f2f1",
    accentColor: "#4db6ac",
    darkMode: false,
    fontStyle: "sans-serif",
    heroImage: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=600",
    previewItems: ["ROI 8.5%", "Opportunità Milano", "Fund #12"],
    preview: {
      headerBg: "#e0f2f1",
      headerText: "#00897b",
      cardBg: "#ffffff",
      accent: "#4db6ac",
      bodyBg: "#e0f2f1",
      layoutStyle: "minimal",
    },
    features: ["Dashboard investimenti", "KPI & Rendimenti", "Opportunità", "Portfolio"],
  },

  // ══════════════════════════════════════════════════════════
  // SALUTE & MEDICO (5 template)
  // ══════════════════════════════════════════════════════════

  {
    id: "health_clinic",
    name: "Studio Medico",
    category: "salute",
    target: "Studi medici, ambulatori",
    ux: "guided",
    primaryColor: "#1976d2",
    secondaryColor: "#e3f2fd",
    accentColor: "#64b5f6",
    darkMode: false,
    fontStyle: "sans-serif",
    heroImage: "https://images.unsplash.com/photo-1519494026892-80bbd2d6fd0d?w=600",
    previewItems: ["Medicina Generale", "Cardiologia", "Dermatologia"],
    preview: {
      headerBg: "#1976d2",
      headerText: "#ffffff",
      cardBg: "#ffffff",
      accent: "#64b5f6",
      bodyBg: "#e3f2fd",
      layoutStyle: "quick-actions",
    },
    features: ["Prenotazione visite", "Referti online", "Telemedicina", "Promemoria"],
  },
  {
    id: "health_telemedicine",
    name: "Telemedicina",
    category: "salute",
    target: "Piattaforme di telemedicina, consulti online",
    ux: "dashboard",
    primaryColor: "#00838f",
    secondaryColor: "#0a0a0a",
    accentColor: "#4dd0e1",
    darkMode: true,
    fontStyle: "sans-serif",
    heroImage: "https://images.unsplash.com/photo-1519494026892-80bbd2d6fd0d?w=600",
    previewItems: ["Video Consulto", "Chat Medico", "Ricetta Digitale"],
    preview: {
      headerBg: "#0a0a0a",
      headerText: "#4dd0e1",
      cardBg: "#1a1a2e",
      accent: "#4dd0e1",
      bodyBg: "#0a0a0a",
      layoutStyle: "dashboard",
    },
    features: ["Video consulti", "Chat medico", "Ricette digitali", "Cartella clinica"],
  },
  {
    id: "health_nutrition",
    name: "Nutrizione",
    category: "salute",
    target: "Nutrizionisti, dietologi, food coach",
    ux: "immersive",
    primaryColor: "#4caf50",
    secondaryColor: "#f1f8e9",
    accentColor: "#81c784",
    darkMode: false,
    fontStyle: "sans-serif",
    heroImage: "https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=600",
    previewItems: ["Piano Alimentare", "Ricette", "Progressi"],
    preview: {
      headerBg: "#f1f8e9",
      headerText: "#4caf50",
      cardBg: "#ffffff",
      accent: "#81c784",
      bodyBg: "#f1f8e9",
      layoutStyle: "minimal",
    },
    features: ["Piani alimentari", "Diario alimentare", "Ricette sane", "Monitoraggio peso"],
  },
  {
    id: "health_psychology",
    name: "Psicologia",
    category: "salute",
    target: "Psicologi, psicoterapeuti, counselor",
    ux: "quick",
    primaryColor: "#7b1fa2",
    secondaryColor: "#f3e5f5",
    accentColor: "#ba68c8",
    darkMode: false,
    fontStyle: "serif",
    heroImage: "https://images.unsplash.com/photo-1519494026892-80bbd2d6fd0d?w=600",
    previewItems: ["Consulenza", "Percorso Individuale", "Mindfulness"],
    preview: {
      headerBg: "#f3e5f5",
      headerText: "#7b1fa2",
      cardBg: "#ffffff",
      accent: "#ba68c8",
      bodyBg: "#f3e5f5",
      layoutStyle: "cards",
    },
    features: ["Prenotazione sedute", "Percorsi terapeutici", "Esercizi", "Journal"],
  },
  {
    id: "health_dental",
    name: "Clinica Dentale",
    category: "salute",
    target: "Dentisti, cliniche odontoiatriche",
    ux: "catalog",
    primaryColor: "#0277bd",
    secondaryColor: "#ffffff",
    accentColor: "#29b6f6",
    darkMode: false,
    fontStyle: "sans-serif",
    heroImage: "https://images.unsplash.com/photo-1519494026892-80bbd2d6fd0d?w=600",
    previewItems: ["Igiene Dentale", "Ortodonzia", "Implantologia"],
    preview: {
      headerBg: "#ffffff",
      headerText: "#0277bd",
      cardBg: "#ffffff",
      accent: "#29b6f6",
      bodyBg: "#f5fbff",
      layoutStyle: "offers",
    },
    features: ["Servizi & Prezzi", "Prenotazione rapida", "Before/After", "Piani trattamento"],
  },

  // ══════════════════════════════════════════════════════════
  // TURISMO & OSPITALITÀ (5 template)
  // ══════════════════════════════════════════════════════════

  {
    id: "tourism_hotel",
    name: "Hotel",
    category: "turismo",
    target: "Hotel, resort, strutture alberghiere",
    ux: "immersive",
    primaryColor: "#c9a96e",
    secondaryColor: "#1a1a1a",
    accentColor: "#d4b896",
    darkMode: true,
    fontStyle: "serif",
    heroImage: "https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=600",
    previewItems: ["Suite Deluxe", "Camera Vista Mare", "Penthouse"],
    preview: {
      headerBg: "transparent",
      headerText: "#ffffff",
      cardBg: "#1a1a1a",
      accent: "#c9a96e",
      bodyBg: "#0a0a0a",
      layoutStyle: "immersive",
      heroImage: "https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=600",
    },
    features: ["Prenota camera", "Servizi hotel", "Ristorante", "Spa & Wellness"],
  },
  {
    id: "tourism_bnb",
    name: "B&B & Guest House",
    category: "turismo",
    target: "B&B, agriturismi, case vacanza",
    ux: "guided",
    primaryColor: "#5d4037",
    secondaryColor: "#faf3e0",
    accentColor: "#8d6e63",
    darkMode: false,
    fontStyle: "serif",
    heroImage: "https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=600",
    previewItems: ["Camera Lavanda", "Suite Giardino", "Appartamento Family"],
    preview: {
      headerBg: "#faf3e0",
      headerText: "#5d4037",
      cardBg: "#ffffff",
      accent: "#8d6e63",
      bodyBg: "#faf3e0",
      layoutStyle: "minimal",
    },
    features: ["Calendario", "Camere", "Colazione", "Esperienze locali"],
  },
  {
    id: "tourism_tour",
    name: "Tour Operator",
    category: "turismo",
    target: "Tour operator, pacchetti viaggio",
    ux: "catalog",
    primaryColor: "#ff6f00",
    secondaryColor: "#fff3e0",
    accentColor: "#ffb74d",
    darkMode: false,
    fontStyle: "sans-serif",
    heroImage: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=600",
    previewItems: ["Tour Costiera", "Safari Kenia", "Crociera Grecia"],
    preview: {
      headerBg: "#fff3e0",
      headerText: "#ff6f00",
      cardBg: "#ffffff",
      accent: "#ffb74d",
      bodyBg: "#fff3e0",
      layoutStyle: "cards",
    },
    features: ["Catalogo tour", "Prenotazione", "Itinerari", "Recensioni"],
  },
  {
    id: "tourism_experience",
    name: "Esperienze",
    category: "turismo",
    target: "Esperienze turistiche, attività locali",
    ux: "quick",
    primaryColor: "#e91e63",
    secondaryColor: "#ffffff",
    accentColor: "#f48fb1",
    darkMode: false,
    fontStyle: "sans-serif",
    heroImage: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=600",
    previewItems: ["Cooking Class", "Wine Tour", "City Walk"],
    preview: {
      headerBg: "#e91e63",
      headerText: "#ffffff",
      cardBg: "#ffffff",
      accent: "#e91e63",
      bodyBg: "#fff5f8",
      layoutStyle: "quick-actions",
    },
    features: ["Esperienze locali", "Prenota subito", "Mappa", "Recensioni verificate"],
  },
  {
    id: "tourism_guide",
    name: "Guida Locale",
    category: "turismo",
    target: "Guide turistiche, escursionisti",
    ux: "dashboard",
    primaryColor: "#2e7d32",
    secondaryColor: "#e8f5e9",
    accentColor: "#66bb6a",
    darkMode: false,
    fontStyle: "sans-serif",
    heroImage: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=600",
    previewItems: ["Tour Privato", "Gruppo 6 pax", "Escursione"],
    preview: {
      headerBg: "#e8f5e9",
      headerText: "#2e7d32",
      cardBg: "#ffffff",
      accent: "#66bb6a",
      bodyBg: "#e8f5e9",
      layoutStyle: "dashboard",
    },
    features: ["Calendario tour", "Prenotazioni", "Lingue parlate", "Contatto diretto"],
  },

  // ══════════════════════════════════════════════════════════
  // FORMAZIONE (5 template)
  // ══════════════════════════════════════════════════════════

  {
    id: "edu_academy",
    name: "Academy Online",
    category: "educazione",
    target: "Piattaforme e-learning, corsi online",
    ux: "dashboard",
    primaryColor: "#6366f1",
    secondaryColor: "#f5f3ff",
    accentColor: "#818cf8",
    darkMode: false,
    fontStyle: "sans-serif",
    heroImage: "https://images.unsplash.com/photo-1522202176988-66273c2fd55f?w=600",
    previewItems: ["Digital Marketing", "UX Design", "Business Strategy"],
    preview: {
      headerBg: "#f5f3ff",
      headerText: "#6366f1",
      cardBg: "#ffffff",
      accent: "#818cf8",
      bodyBg: "#f5f3ff",
      layoutStyle: "dashboard",
    },
    features: ["Catalogo corsi", "Progressi", "Certificati", "Community"],
  },
  {
    id: "edu_coaching",
    name: "Life Coaching",
    category: "educazione",
    target: "Coach, mentor, formatori",
    ux: "immersive",
    primaryColor: "#ff7043",
    secondaryColor: "#0a0a0a",
    accentColor: "#ffab91",
    darkMode: true,
    fontStyle: "serif",
    heroImage: "https://images.unsplash.com/photo-1522202176988-66273c2fd55f?w=600",
    previewItems: ["1-to-1 Session", "Group Workshop", "Retreat"],
    preview: {
      headerBg: "transparent",
      headerText: "#ffffff",
      cardBg: "#1a1a1a",
      accent: "#ff7043",
      bodyBg: "#0a0a0a",
      layoutStyle: "immersive",
      heroImage: "https://images.unsplash.com/photo-1522202176988-66273c2fd55f?w=600",
    },
    features: ["Percorsi coaching", "Prenota sessione", "Risorse", "Testimonianze"],
  },
  {
    id: "edu_school",
    name: "Scuola",
    category: "educazione",
    target: "Scuole, istituti, centri formazione",
    ux: "quick",
    primaryColor: "#1976d2",
    secondaryColor: "#ffffff",
    accentColor: "#64b5f6",
    darkMode: false,
    fontStyle: "sans-serif",
    heroImage: "https://images.unsplash.com/photo-1522202176988-66273c2fd55f?w=600",
    previewItems: ["Corsi 2024", "Iscrizioni", "Calendario"],
    preview: {
      headerBg: "#1976d2",
      headerText: "#ffffff",
      cardBg: "#ffffff",
      accent: "#1976d2",
      bodyBg: "#e3f2fd",
      layoutStyle: "quick-actions",
    },
    features: ["Iscrizioni online", "Calendario corsi", "Comunicazioni", "Pagamenti"],
  },
  {
    id: "edu_tutor",
    name: "Lezioni Private",
    category: "educazione",
    target: "Tutor privati, ripetizioni",
    ux: "guided",
    primaryColor: "#00897b",
    secondaryColor: "#e0f2f1",
    accentColor: "#4db6ac",
    darkMode: false,
    fontStyle: "sans-serif",
    heroImage: "https://images.unsplash.com/photo-1522202176988-66273c2fd55f?w=600",
    previewItems: ["Matematica", "Inglese", "Fisica"],
    preview: {
      headerBg: "#e0f2f1",
      headerText: "#00897b",
      cardBg: "#ffffff",
      accent: "#4db6ac",
      bodyBg: "#e0f2f1",
      layoutStyle: "minimal",
    },
    features: ["Materie", "Prenota lezione", "Materiale didattico", "Progressi studente"],
  },
  {
    id: "edu_corporate",
    name: "Formazione Aziendale",
    category: "educazione",
    target: "Formazione per aziende, HR training",
    ux: "catalog",
    primaryColor: "#37474f",
    secondaryColor: "#eceff1",
    accentColor: "#78909c",
    darkMode: false,
    fontStyle: "sans-serif",
    heroImage: "https://images.unsplash.com/photo-1522202176988-66273c2fd55f?w=600",
    previewItems: ["Leadership", "Team Building", "Compliance"],
    preview: {
      headerBg: "#eceff1",
      headerText: "#37474f",
      cardBg: "#ffffff",
      accent: "#78909c",
      bodyBg: "#eceff1",
      layoutStyle: "cards",
    },
    features: ["Catalogo formazione", "Dashboard HR", "Certificazioni", "Report"],
  },

  // ══════════════════════════════════════════════════════════
  // ALTRO (5 template)
  // ══════════════════════════════════════════════════════════

  {
    id: "other_community",
    name: "Community",
    category: "altro",
    target: "Community online, gruppi, forum",
    ux: "dashboard",
    primaryColor: "#6366f1",
    secondaryColor: "#0f0f1a",
    accentColor: "#a78bfa",
    darkMode: true,
    fontStyle: "sans-serif",
    heroImage: "https://images.unsplash.com/photo-1522202176988-66273c2fd55f?w=600",
    previewItems: ["Feed", "Gruppi", "Eventi"],
    preview: {
      headerBg: "#0f0f1a",
      headerText: "#a78bfa",
      cardBg: "#1a1a2e",
      accent: "#a78bfa",
      bodyBg: "#0f0f1a",
      layoutStyle: "dashboard",
    },
    features: ["Feed sociale", "Gruppi", "Messaggistica", "Eventi community"],
  },
  {
    id: "other_club",
    name: "Club Membri",
    category: "altro",
    target: "Club esclusivi, circoli, associazioni",
    ux: "immersive",
    primaryColor: "#c9a96e",
    secondaryColor: "#1a1a1a",
    accentColor: "#e8c49a",
    darkMode: true,
    fontStyle: "serif",
    heroImage: "https://images.unsplash.com/photo-1522202176988-66273c2fd55f?w=600",
    previewItems: ["Membership", "Vantaggi", "Area Riservata"],
    preview: {
      headerBg: "transparent",
      headerText: "#ffffff",
      cardBg: "#1a1a1a",
      accent: "#c9a96e",
      bodyBg: "#0a0a0a",
      layoutStyle: "immersive",
      heroImage: "https://images.unsplash.com/photo-1522202176988-66273c2fd55f?w=600",
    },
    features: ["Iscrizione", "Directory membri", "Eventi esclusivi", "Vantaggi"],
  },
  {
    id: "other_events",
    name: "Eventi",
    category: "altro",
    target: "Organizzazione eventi, conferenze, fiere",
    ux: "catalog",
    primaryColor: "#e91e63",
    secondaryColor: "#ffffff",
    accentColor: "#f48fb1",
    darkMode: false,
    fontStyle: "sans-serif",
    heroImage: "https://images.unsplash.com/photo-1522202176988-66273c2fd55f?w=600",
    previewItems: ["Conference 2024", "Workshop", "Networking"],
    preview: {
      headerBg: "#ffffff",
      headerText: "#e91e63",
      cardBg: "#ffffff",
      accent: "#f48fb1",
      bodyBg: "#fff5f8",
      layoutStyle: "cards",
    },
    features: ["Catalogo eventi", "Biglietti", "Programma", "Speaker"],
  },
  {
    id: "other_network",
    name: "Network Professionale",
    category: "altro",
    target: "Network B2B, associazioni professionali",
    ux: "quick",
    primaryColor: "#0d47a1",
    secondaryColor: "#e3f2fd",
    accentColor: "#42a5f5",
    darkMode: false,
    fontStyle: "sans-serif",
    heroImage: "https://images.unsplash.com/photo-1522202176988-66273c2fd55f?w=600",
    previewItems: ["Directory", "Matchmaking", "News"],
    preview: {
      headerBg: "#0d47a1",
      headerText: "#ffffff",
      cardBg: "#ffffff",
      accent: "#42a5f5",
      bodyBg: "#e3f2fd",
      layoutStyle: "quick-actions",
    },
    features: ["Directory membri", "Matchmaking", "News & Articoli", "Messaggistica"],
  },
  {
    id: "other_local",
    name: "Servizi Locali",
    category: "altro",
    target: "Servizi di quartiere, attività locali",
    ux: "guided",
    primaryColor: "#4caf50",
    secondaryColor: "#f1f8e9",
    accentColor: "#81c784",
    darkMode: false,
    fontStyle: "sans-serif",
    heroImage: "https://images.unsplash.com/photo-1522202176988-66273c2fd55f?w=600",
    previewItems: ["Idraulico", "Elettricista", "Giardiniere"],
    preview: {
      headerBg: "#f1f8e9",
      headerText: "#4caf50",
      cardBg: "#ffffff",
      accent: "#81c784",
      bodyBg: "#f1f8e9",
      layoutStyle: "offers",
    },
    features: ["Cerca servizio", "Preventivi", "Recensioni", "Prenotazione"],
  },
];

// Mappa categorie per il wizard
export const CATEGORY_MAP = {
  ristorazione: "ristorazione",
  beauty: "beauty",
  fitness: "fitness",
  ecommerce: "ecommerce",
  servizi: "servizi",
  immobiliare: "immobiliare",
  salute: "salute",
  turismo: "turismo",
  educazione: "educazione",
  altro: "altro",
};

export default TEMPLATE_LIBRARY;